create table items
(
    id               bigint generated by default as identity
        primary key,
    category         varchar(255),
    description      varchar(255),
    inventory_number varchar(255)
        constraint ukkyyvsbi4cirgm2ovmc5ige0br
            unique,
    name             varchar(255),
    status           varchar(255)
        constraint items_status_check
            check ((status)::text = ANY
        ((ARRAY ['AVAILABLE'::character varying, 'RENTED'::character varying, 'MAINTENANCE'::character varying])::text[]))
    );

create table users
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    email      varchar(255) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    password   varchar(255) not null,
    role       varchar(255)
        constraint users_role_check
            check ((role)::text = ANY
        ((ARRAY ['ROLE_USER'::character varying, 'ROLE_ADMIN'::character varying])::text[]))
    );

create table rentals
(
    id                   bigint generated by default as identity
        primary key,
    actual_return_date   date,
    expected_return_date date,
    start_date           date,
    status               varchar(255)
        constraint rentals_status_check
            check ((status)::text = ANY ((ARRAY ['ACTIVE'::character varying, 'RETURNED'::character varying])::text[])),
    item_id              bigint
        constraint fk9t4jdsn113em9kyh6wkl81efm
            references items,
    user_id              bigint
        constraint fktnhd1objf2mlb6ag6k726u269
            references users
);